name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Altere para a versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit
      run: streamlit run home.py  # Substitua pelo comando correto para seu deploy
      env:
        STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
